title: The ELIXIR Research Software Ecosystem
# This appears in the html browser tab for the site title (seen mostly by search engines, not users)

# topnav_title: ELIXIR toolkit theme
# Optional: this appears on the top navigation bar next to the main_logo.svg icon

description: >- # this means to ignore newlines until "baseurl:"
  The Research Software Ecosystem (RSEc) aims to act as a resource for collecting,
  maintaining, sharing, and preserving high-quality information (“metadata”) about 
  research software across scientific applications, building upon the ELIXIR’s work 
  in life sciences.
# Metadata description of the website

remote_theme: ELIXIR-Belgium/elixir-toolkit-theme@3.0.0

exclude:
  - .gitignore
  - var/
  - vendor
  - Gemfile*
  - LICENSE

sass:
    style: compressed

defaults:
# Define here page metadata attributes for all pages at once or on specific directories. More information: https://jekyllrb.com/docs/configuration/front-matter-defaults/
  -
    scope:
      path: ""
      type: "pages"
    values:
      permalink: /:basename
      layout: "page"

plugins:
  - elixir-toolkit-theme-plugins
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-github-metadata
  - jemoji
  - webrick


theme_variables: 
 topnav:
   brand_logo: assets/img/logo-rsec.svg


exclude:
  - README.md
  - .gitignore
  - var/
  - vendor
  - Gemfile*
  - LICENSE
